FROM mcr.microsoft.com/devcontainers/base:ubuntu

# [Optional] Install additional OS packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>

# [Optional] Set the default shell to zsh (though common-utils feature usually handles this)
ENV SHELL /bin/zsh
