// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0--rc1
// source: proto/seraphine.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SeraphineService_GetProjectState_FullMethodName = "/seraphine.SeraphineService/GetProjectState"
	SeraphineService_RegisterProject_FullMethodName = "/seraphine.SeraphineService/RegisterProject"
)

// SeraphineServiceClient is the client API for SeraphineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SeraphineServiceClient interface {
	GetProjectState(ctx context.Context, in *GetProjectStateRequest, opts ...grpc.CallOption) (*GetProjectStateResponse, error)
	RegisterProject(ctx context.Context, in *RegisterProjectRequest, opts ...grpc.CallOption) (*RegisterProjectResponse, error)
}

type seraphineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSeraphineServiceClient(cc grpc.ClientConnInterface) SeraphineServiceClient {
	return &seraphineServiceClient{cc}
}

func (c *seraphineServiceClient) GetProjectState(ctx context.Context, in *GetProjectStateRequest, opts ...grpc.CallOption) (*GetProjectStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProjectStateResponse)
	err := c.cc.Invoke(ctx, SeraphineService_GetProjectState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seraphineServiceClient) RegisterProject(ctx context.Context, in *RegisterProjectRequest, opts ...grpc.CallOption) (*RegisterProjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterProjectResponse)
	err := c.cc.Invoke(ctx, SeraphineService_RegisterProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SeraphineServiceServer is the server API for SeraphineService service.
// All implementations must embed UnimplementedSeraphineServiceServer
// for forward compatibility.
type SeraphineServiceServer interface {
	GetProjectState(context.Context, *GetProjectStateRequest) (*GetProjectStateResponse, error)
	RegisterProject(context.Context, *RegisterProjectRequest) (*RegisterProjectResponse, error)
	mustEmbedUnimplementedSeraphineServiceServer()
}

// UnimplementedSeraphineServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSeraphineServiceServer struct{}

func (UnimplementedSeraphineServiceServer) GetProjectState(context.Context, *GetProjectStateRequest) (*GetProjectStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProjectState not implemented")
}
func (UnimplementedSeraphineServiceServer) RegisterProject(context.Context, *RegisterProjectRequest) (*RegisterProjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterProject not implemented")
}
func (UnimplementedSeraphineServiceServer) mustEmbedUnimplementedSeraphineServiceServer() {}
func (UnimplementedSeraphineServiceServer) testEmbeddedByValue()                          {}

// UnsafeSeraphineServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SeraphineServiceServer will
// result in compilation errors.
type UnsafeSeraphineServiceServer interface {
	mustEmbedUnimplementedSeraphineServiceServer()
}

func RegisterSeraphineServiceServer(s grpc.ServiceRegistrar, srv SeraphineServiceServer) {
	// If the following call panics, it indicates UnimplementedSeraphineServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SeraphineService_ServiceDesc, srv)
}

func _SeraphineService_GetProjectState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProjectStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeraphineServiceServer).GetProjectState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeraphineService_GetProjectState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeraphineServiceServer).GetProjectState(ctx, req.(*GetProjectStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeraphineService_RegisterProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeraphineServiceServer).RegisterProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeraphineService_RegisterProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeraphineServiceServer).RegisterProject(ctx, req.(*RegisterProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SeraphineService_ServiceDesc is the grpc.ServiceDesc for SeraphineService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SeraphineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "seraphine.SeraphineService",
	HandlerType: (*SeraphineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProjectState",
			Handler:    _SeraphineService_GetProjectState_Handler,
		},
		{
			MethodName: "RegisterProject",
			Handler:    _SeraphineService_RegisterProject_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/seraphine.proto",
}
